version: "3.9"

networks:
  backend:
    driver: bridge

volumes:
  postgres_data_quickgig:
  pgadmin_data_quickgig:

services:
  postgres:
    container_name: postgres_container
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres_data_quickgig:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - backend
    volumes:
      - pgadmin_data_quickgig:/var/lib/pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
